target-version = "py312"

# E/W - стиль PEP8, F - критические ошибки кода, I - автоматическая сортировка импортов (isort)
select = ["E", "W", "F", "I"]
ignore = []

[isort]
# Объединять импорты из одного и того же модуля и делать ровно 2 пустые строки после блока импортов
combine-as-imports = true
lines-after-imports = 2
